services:
  tg-watchbot:
    build: .
    container_name: tg-watchbot
    restart: unless-stopped
    ports:
      - "8765:8765"
    environment:
      WEB_PANEL_HOST: "0.0.0.0"
    volumes:
      - ./.env:/app/.env
      - ./config.yaml:/app/config.yaml
      - ./tg-watchbot.sqlite3:/app/tg-watchbot.sqlite3
      - ./tg-watchbot.log:/app/tg-watchbot.log
